# Generated by Django 4.2.16 on 2024-11-18 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='iamge',
            new_name='image',
        ),
    ]
