# Generated by Django 4.2.16 on 2024-11-18 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_loanproducts_loanoptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanproducts',
            name='loan_lmt',
            field=models.TextField(null=True),
        ),
    ]
